### ISSUE TITLE
Find in Buffer issue

### ISSUE THREAD

**Issue by alexchee** [andyjeffries/ruby-string-interpolation#5]
This action is triggering even if the editor is out of focus. I'm having a problem where I'm trying to find in buffer and if I type in '#', it'll do the interpolation where my cursor was and not insert it into the find field.

Steps to replace:
1. Open ruby file, click somewhere in text
2. Open "Find in Buffer"
3. type "#"

Behavior:
Inserts "#" into position where cursor and doesn't insert # in the find field.

Expected Behavior:
Should insert # into find field instead of the editor.

Sorry if this looks too formal, I've been writing too many bug reports lately.

**Comment by alexchee** [comment]
Pull request #2 fixes this.

**Comment by andyjeffries** [comment]
Merged and I'm about to publish a new release.
